### PR TITLE
Meson support and Continuous Integration (Linux, OSX)

### PR DESCRIPTION
**Pull request by zeehio**
This pull request brings meson build support to speech tools:

Test it with:

    meson setup --prefix $PWD/install builddir/
    cd builddir
    meson compile
    meson test # run testsuite
    meson install # copy binaries, headers and installation material into $PWD/install (or your prefix of choice)

If you want to run binaries once installed, make sure the `LD_LIBRARY_PATH` directory is set as required (you will usually need `export LD_LIBRARY_PATH=/your/installation/prefix/lib/` or `export LD_LIBRARY_PATH=/your/installation/prefix/lib/x86_64-linux-gnu/` on Debian and its derivatives)

### CODE REVIEW

**Review by lenzo-duo — CHANGES_REQUESTED** [review]
Please add meson build instructions to INSTALL

**Review by lenzo-duo — APPROVED** [review]

**Review by lenzo-duo — CHANGES_REQUESTED** [review]
$ meson setup --prefix=installdir -Daudio_pulseaudio=false builddir

ERROR: Neither directory contains a build file meson.build.


Can you also make audio_pulseaudio=false the default

**Comment by lenzo-duo** [comment]
Hi -- I'd like to add this if you can make just a couple more changes (above).

**Comment by zeehio** [comment]
Sure. I hope to find some time this weekend. I've been too busy lately

**Comment by zeehio** [comment]
The default for pulseaudio was set to "auto". That enables the pulseaudio module only when the pulseaudio libraries and headers are found. I have set it to "disabled" now as requested, so users/maintainers need to enable it manually they want it. Is the pulseaudio module buggy?

I've added the continuous integration for linux and OSX, both with makefile and meson build system. If you still have trouble building this on your system please tell me.

**Review by lenzo-duo — APPROVED** [review]

**Comment by lenzo-duo** [comment]
auto would be fine for pulseaudio -- I didn't catch that before. Feel free to submit a PR if you'd like for that

**Comment by lenzo-duo** [comment]
LGTM, built both ways and tested

**Pull request merged**
